version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "maven"
    # Specify to recursively search for pom.xml files
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
