sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2/repository/
before_install:
- git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git target/ci-tooling
- cp target/ci-tooling/maven-settings-for-openfire-plugins.xml $HOME/.m2/settings.xml
before_script:
- gem install travis
script: mvn verify -P ci
install: true
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml  -P ci
  skip_cleanup: true
  on:
    all_branches: true
after_deploy:
- curl -LO https://raw.github.com/igniterealtime/ci-tooling/master/trigger-travis.sh
- chmod +x trigger-travis.sh
- DOWNSTREAM=bookmarks callbackOnOffline candy certificateManager clientControl contentFilter dbaccess emailListener emailOnAway externalservicediscovery fastpath gojara hazelcast httpFileUpload inverse jingleNodes jmxweb justmarried loadStats monitoring motd mucservice nodejs nonSaslAuthentication packetFilter presence registration restAPI search sip stunserver subscription tikitoken userCreation userImportExport userservice userStatus xmldebugger
- for pluginname in $DOWNSTREAM; do; sleep 1; ./trigger-travis.sh igniterealtime openfire-$pluginname-plugin $TRAVIS_ACCESS_TOKEN; done;
env:
  global:
  - secure: LNW7mcZ0HOXVXQ9r3h9CgMYVHqCleyC8Mbffl6iDOi3Z/McJUqjvAsop16RRPhgBiVePt1Y9pqZnWjm4jBHacttsH8m5p22T/XMW3T3/J1ovJUK5L/hvhXpVMH8GXTp3dk+Wsylh/39cmgW59TRmkFUXM2FbDpyJdAJqNaSreW0=
  - secure: iUybxreNImeViBr3vofRatXhC7nYra5AyKVJTuJ1lQvljbFu+5WCXmZbPpPK4bxANCyaQC5Ny+QtqZrCgrD392CXKCk9K24kbQGLLX1jCcApF4EY3l/5LQwjMgCLgmqynkzmZC6AzYm+/ESXmrZcsnxa5g7FCFd6wvVAV+Y/K/M=
