<?php

$settings = array (
    'header_textcolor' => '003044',
    'background_color' => '',
    'background_image' => '',
    'background_repeat' => 'repeat',
    'background_position_x' => 'left',
    'background_attachment' => 'fixed',
    'site_title_font_family' => '"Ubuntu Condensed", "Droid Sans", "Helvetica Neue", Tahoma, Arial, sans-serif',
    
    'header_height' => 'auto',
    'header_height_note' => '',
    'header_height_home' => 'auto',
    'header_height_home_note' => '',
    'header_width' => 'fullwidth',
    'header_width_note' => '',
    
    'fixed_top_nav' => true,
    'use_dark_colors' => '',
    'dark_bottom_nav' => '',
  
    'title_font_family' => '"Ubuntu Condensed", "Droid Sans", "Helvetica Neue", Tahoma, Arial, sans-serif',
    'title_font_color' => '003044',


    'h1_font_size' => '48px',
    'h2_font_size' => '32px',
    'h3_font_size' => '28px',
    'h4_font_size' => '24px',
    'h5_font_size' => '22px',
    'h6_font_size' => '20px',
    'cc_list_post_style' => 'blog-style',

    
    'blog_archive_post_meta' => '',
    
    
    'cc_slideshow_template' => 'tine',
    'cc2_slideshow_style' => 'bubble-preview',
    'cc_slider_display' => 'home',
    'cc_slider_position' => 'cc_first_inside_main_content',
    'slider_effect_title' => 'bounceInLeft',
    'slider_effect_excerpt' => 'bounceInRight',
    'cc_slider_text_align' => 'center',
    'caption_title_bg_color' => 'ffffff',
    'caption_title_font_color' => '003044',
    'caption_title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
    'caption_title_shadow' => true,
    'caption_title_opacity' => '0.8',
    'caption_text_bg_color' => 'FBFBFB',
    'caption_text_font_color' => '333',
    'caption_text_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
    'caption_text_font_weight' => '',
    'caption_text_font_style' => '',
    'caption_text_shadow' => true,
    'caption_text_opacity' => '0.9',
    'cc_slider_height' => '420px',
    'cc_sliding_time' => '7000',
    'display_slider_nav' => true,
    'nav_menu_locations' => 
    array (
      'top' => 2,
      'secondary' => 0,
    ),
    'header_background_color' => 'fff',
    'font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
    'google_fonts_note' => '',
    'font_color' => '494949',
    'link_color' => '436882',
    'hover_color' => '6ca4d8',
    'link_underline' => 'just for mouse over',
    'widget_title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
    'widget_title_background_color' => '',

    'cc_slider_width' => '1170',
    'tagline_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
    'tagline_text_color' => 'a9a9a9',
    'header_background_image' => '',
    'top_nav_position' => 'left',
    'secondary_nav_position' => 'left',
    'heading_nav_use_dark_colors' => '',
    'color_scheme_top_nav' => 'light',
    'color_scheme_bottom_nav' => 'light',

    'top_nav_background_color' => 'f2f2f2',
    'top_nav_text_color' => '898989',
    'top_nav_hover_text_color' => '003044',
    'secondary_nav_background_color' => 'f2f2f2',
    'secondary_nav_text_color' => '686868',
    'secondary_nav_hover_text_color' => '003044',
    'top_nav_brand_text_color' => '003044',
    'top_nav_brand_image' => '',
    'bottom_nav_brand_text_color' => '',
    'bottom_nav_brand_image' => '',

    'widget_title_text_color' => '',
    'widget_title_font_size' => '',
    'widget_background_color' => '',
    'widget_link_color' => '',
    'widget_link_text_hover_color' => '',
    'bootstrap_typography_note' => '',
    'footer_fullwidth_note' => '',
    'footer_fullwidth_background_image' => '',
    'footer_fullwidth_background_color' => 'eee',
    'footer_fullwidth_border_top_color' => 'ddd',
    'footer_fullwidth_border_bottom_color' => 'e5e5e5',

    'header_image' => 'remove-header',
    'top_nav_font_family' => 'inherit',
    'top_nav_font_size' => '18px',
    'top_nav_hover_background_color' => '608280',
    'top_nav_active_background_color' => 'f9f9f9',
    'top_nav_active_text_color' => 'b7b7b7',
    'top_nav_dropdown_background_color' => 'e0e0e0',
    'top_nav_dropdown_text_color' => '686868',
    'top_nav_dropdown_hover_background_color' => '608280',
    'top_nav_dropdown_hover_text_color' => 'fff',
    'secondary_nav_hover_background_color' => '608280',
    'secondary_nav_active_background_color' => 'f9f9f9',
    'secondary_nav_active_text_color' => 'b7b7b7',
    'secondary_nav_dropdown_background_color' => 'f4f4f4',
    'secondary_nav_dropdown_text_color' => '003044',
    'secondary_nav_dropdown_hover_background_color' => '4b8589',
    'secondary_nav_dropdown_hover_text_color' => 'fff',
    'widgets_header' => 
    array (
      'title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
      'title_font_size' => '',
      'title_font_weight' => '',
      'title_text_color' => '003044',
      'title_background_color' => '',
      'background_color' => '',
      'link_color' => '77a8b7',
      'link_hover_color' => '608280',
      'link_hover_background_color' => '',
    ),
    'widgets_footer_fullwidth' => 
    array (
      'title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
      'title_font_size' => '',
      'title_font_weight' => '',
      'title_text_color' => '003044',
      'title_background_color' => '',
      'background_color' => '',
      'link_color' => '77a8b7',
      'link_hover_color' => '',
      'link_hover_background_color' => '608280',
    ),
    'widgets_footer_column' => 
    array (
      'title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
      'title_font_size' => '',
      'title_font_weight' => '',
      'title_text_color' => '77a8b7',
      'title_background_color' => '',
      'background_color' => '',
      'link_color' => '77a8b7',
      'link_hover_color' => '08677f',
      'link_hover_background_color' => '',
    ),

    'footer_column_background_image' => '',
    'footer_column_background_color' => 'eee',
    'footer_column_border_top_color' => 'ddd',
    'footer_column_border_bottom_color' => 'c4c4c4',
    'headline_footer_credits' => '',
    'footer_branding_show_credits' => true,
    'footer_branding_custom_credits' => '',
    'bootstrap_scroll_top' => 
    array (
      'link_color' => '77a8b7',
      'hover_text_color' => '003044',
      'icon_size' => '18px',
      'button_icon_class' => 'glyphicon glyphicon-chevron-up',
      'font_size' => '18px',
      'button_text' => 'Back to Top',
      'button_link' => '#masthead',
      'height' => '18',
      'position' => 'right',
      'position_offset' => 10,
      'offset' => '100',
    ),
);

