<?php
/**
 * Dark color scheme
 * 
 * @package cc2
 * @since 2.0.20
 */

$settings = array(
    'header_textcolor' => '728fa8',
    'background_color' => '050505',
   /*
    'font_color' => 'cecece',
    'link_color' => '6e9aad',
    'hover_color' => '31526b',
    */
    'top_nav_hover_background_color' => 'd6d6d6',
    'top_nav_active_background_color' => 'd6d6d6',
    'top_nav_active_text_color' => 'b7b7b7',
    'top_nav_dropdown_background_color' => 'd6d6d6',
    'top_nav_dropdown_text_color' => '8c8c8c',
    'top_nav_dropdown_hover_background_color' => '31526b',
    'secondary_nav_hover_background_color' => 'd6d6d6',
    'secondary_nav_active_background_color' => 'd6d6d6',
    'secondary_nav_active_text_color' => 'b7b7b7',
    'secondary_nav_dropdown_background_color' => 'd6d6d6',
    'secondary_nav_dropdown_text_color' => '8c8c8c',
    'secondary_nav_dropdown_hover_background_color' => '31526b',
    'footer_column_border_bottom_color' => 'c4c4c4',
    'tagline_text_color' => 'cecece',
    'title_font_color' => '015670',
    'header_background_color' => '050505',
    'top_nav_background_color' => '31526b',
    'top_nav_text_color' => '8c8c8c',
    'top_nav_hover_text_color' => '353231',
    'secondary_nav_background_color' => '31526b',
    'secondary_nav_text_color' => '8c8c8c',
    'secondary_nav_hover_text_color' => '353231',
    'top_nav_brand_text_color' => '003044',
    'caption_title_bg_color' => 'ffffff',
    'caption_title_font_color' => '003044',
    'caption_text_bg_color' => 'FBFBFB',
    'caption_text_font_color' => '333',
    'footer_fullwidth_border_top_color' => 'ddd',
    'footer_fullwidth_border_bottom_color' => 'e5e5e5',
    'site_title_font_family' => '"Lato", "Droid Sans", "Helvetica Neue", Tahoma, Arial, sans-serif',
    'site_title_position' => 'left',
    'display_header_home' => true,
    'display_header_posts' => true,
    'display_header_pages' => true,
    'display_header_archive' => true,
    'display_header_search' => true,
    'display_header_404' => true,
    'header_height' => 'auto',
    'header_height_home' => 'auto',
    'header_width' => 'fullwidth',
    'fixed_top_nav' => true,
    'top_nav_brand' => true,
    'default_layout' => 'right',
    'default_page_layout' => 'right',
    'default_post_layout' => 'right',
    'default_archive_layout' => 'right',
    'title_font_family' => '"Lato", "Droid Sans", "Helvetica Neue", Tahoma, Arial, sans-serif',
    'h1_font_size' => '48px',
    'h2_font_size' => '32px',
    'h3_font_size' => '28px',
    'h4_font_size' => '24px',
    'h5_font_size' => '22px',
    'h6_font_size' => '20px',
    'cc_list_post_style' => 'blog-style',
    'show_date' => true,
    'show_category' => true,
    'show_author' => true,
    'single_show_date' => true,
    'single_show_category' => true,
    'single_show_author' => true,
    'cc2_slideshow_style' => 'bubble-preview',
    'cc_slider_display' => 'home',
    'cc_slider_position' => 'cc_first_inside_main_content',
    'slider_effect_title' => 'bounceInLeft',
    'slider_effect_excerpt' => 'bounceInRight',
    'cc_slider_text_align' => 'center',
    'caption_title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
    'caption_title_shadow' => true,
    'caption_title_opacity' => '0.8',
    'caption_text_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
    'caption_text_shadow' => true,
    'caption_text_opacity' => '0.9',
    'cc_slider_height' => '420px',
    'cc_sliding_time' => '7000',
    'display_slider_nav' => true,
    /*'font_family' => '"Lato", "Droid Sans", "Helvetica Neue", Tahoma, Arial, sans-serif',*/
    'link_underline' => 'just for mouse over',
    'widget_title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
    'hide_left_sidebar_on_phones' => true,
    'cc_slider_width' => '1170',
    'tagline_font_family' => '"Lato", "Droid Sans", "Helvetica Neue", Tahoma, Arial, sans-serif',
    'top_nav_position' => 'left',
    'secondary_nav_position' => 'left',
    'color_scheme_top_nav' => 'custom',
    'color_scheme_bottom_nav' => 'light',
    'footer_fullwidth_background_color' => 'eee',
    'show_author_image' => 
    array (
      'archive' => false,
      'single_post' => false,
    ),
    'header_image' => 'remove-header',
    'top_nav_font_family' => '"Lato", "Droid Sans", "Helvetica Neue", Tahoma, Arial, sans-serif',
    'top_nav_font_size' => '24px',
    'top_nav_dropdown_hover_text_color' => 'd6d6d6',
    'secondary_nav_dropdown_hover_text_color' => 'd6d6d6',
    'widgets_header' => 
    array (
      'title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
      'title_text_color' => '003044',
      'link_color' => '77a8b7',
      'link_hover_color' => '608280',
    ),
    'widgets_footer_fullwidth' => 
    array (
      'title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
      'title_text_color' => '003044',
      'link_color' => '77a8b7',
      'link_hover_background_color' => '608280',
    ),
    'widgets_footer_column' => 
    array (
      'title_font_family' => '"Century Gothic", "Avant Garde", Arial, sans-serif',
      'title_text_color' => '77a8b7',
      'link_color' => '77a8b7',
      'link_hover_color' => '08677f',
    ),
    'footer_column_background_color' => 'eee',
    'footer_column_border_top_color' => 'ddd',
    'footer_branding_show_credits' => true,
    'bootstrap_scroll_top' => 
    array (
      'link_color' => '77a8b7',
      'hover_text_color' => '003044',
      'icon_size' => '18px',
      'button_icon_class' => 'glyphicon glyphicon-chevron-up',
      'font_size' => '18px',
      'button_text' => 'Back to Top',
      'button_link' => '#masthead',
      'height' => '18',
      'position' => 'right',
      'position_offset' => 10,
      'offset' => '100',
    ),
    'display_footer' => true,
);
